# -*- mode: ruby -*-
# vi: set ft=ruby :

# Copyright Bosch Software Innovations GmbH, 2016.
# Part of the SW360 Portal Project.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html

Vagrant.configure("2") do |config|
  config.vm.box = "trusty64"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true if Vagrant::VERSION =~ /^1.8/
    v.customize ["modifyvm", :id, "--memory", "4096"]
    v.customize ["modifyvm", :id, "--cpus", "2"]
    # v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end

  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision "shell",
                      run: "always",
                      inline: <<-SHELL
set -ex

add-apt-repository ppa:openjdk-r/ppa # for openjdk-8-jre
apt-get update
apt-get install -y openjdk-8-jre
update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

dpkg -i /vagrant/_DEBS/sw360-dependencies_*_amd64.deb || apt-get -f -y install
dpkg -i /vagrant/_DEBS/sw360_*_amd64.deb || sudo apt-get -f -y install
SHELL

  config.vm.network "forwarded_port", guest: 5005, host: 5005
  config.vm.network "forwarded_port", guest: 5984, host: 5984
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  # config.vm.network "forwarded_port", guest: 8443, host: 8443
end
