# coding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Copyright Bosch Software Innovations GmbH, 2016.
# Part of the SW360 Portal Project.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.2"

  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true if Vagrant::VERSION =~ /^1.8/
    v.customize ["modifyvm", :id, "--memory", "4096"]
    v.customize ["modifyvm", :id, "--cpus", "2"]
    # v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end

  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision "shell",
                      run: "always",
                      inline: <<-SHELL
set -ex

yum install -y wget
wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
rpm -Uvh epel-release-latest-7.noarch.rpm

sudo yum --nogpgcheck -y localinstall /vagrant/RPMS/*.rpm
SHELL

  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8443, host: 8443
  config.vm.network "forwarded_port", guest: 5984, host: 5984
  config.vm.network "forwarded_port", guest: 5005, host: 5005
end
