# Copyright Bosch Software Innovations GmbH, 2016.
# Part of the SW360 Portal Project.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html

ROOT=pwd
STATIC_DIR="#{ROOT}/static"
TMP_DIR="#{ROOT}/_tmp"
BUILD_DIR="#{ROOT}/_build"
CACHE_DIR="#{ROOT}/_cache"
OUTPUT_DIR=ENV['OUTPUT_DIR'] || "#{ROOT}/_output"
TARGET_PREFIX=ENV['TARGET_PREFIX'] || "/opt/sw360"

require_relative "build_configuration.rb"

task :default => :all

def wget(urls)
  urls.each do |url|
    mkdir_p CACHE_DIR
    sh "wget -c -N -P #{CACHE_DIR} #{url}"
  end
end

def deployStaticFiles(files)
  files.each do |source, dest|
    mkdir_p "#{dest}"
    cp("#{STATIC_DIR}/#{source}", dest)
    chmod 0644, "#{dest}/#{File.basename(source)}"
  end
end

desc "clean up"
task :clean do
  rm_rf BUILD_DIR
  rm_rf TMP_DIR
  rm_rf(Dir.glob("#{CACHE_DIR}/*"))
  rm_rf(Dir.glob("#{OUTPUT_DIR}/*"))
end

task :fetch_all => ["liferay:fetch",
                    "apache_tomcat:fetch",
                    "couchdb_lucene:fetch"]

desc "build the container with all the dependencies for SW360"
task :container => ["apache_tomcat:apache_tomcat",
                    "couchdb_lucene:couchdb_lucene",
                    "liferay:liferay"]

desc "build the container and predeploy the wars in it"
task :all => [:container]

namespace :install do
    task :copy do
        cp_r(BUILD_DIR,TARGET_PREFIX)
    end
    task :postinstall do
        sh "#{ROOT}/static/postinstall.sh"
    end
end
desc "replaces the folder #{TARGET_PREFIX} with the generated #{BUILD_DIR}. Also calls the postinstall script"
task :install => ["install:copy", "install:postinstall"]

require_relative "rake/apache_tomcat.rb"
require_relative "rake/couchdb_lucene.rb"
require_relative "rake/liferay.rb"
require_relative "rake/docker.rb"
require_relative "rake/package.rb"
