# -*- mode: ruby -*-
# vi: set ft=ruby :

# Copyright Bosch Software Innovations GmbH, 2016.
# Part of the SW360 Portal Project.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html

Vagrant.configure("2") do |config|
  if Vagrant.has_plugin?("vbguest")
    config.vbguest.auto_update = true
  end

  config.vm.box = "trusty64"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true if Vagrant::VERSION =~ /^1.8/
    v.customize ["modifyvm", :id, "--memory", "4096"]
    v.customize ["modifyvm", :id, "--cpus", "2"]
    # v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    v.name = "sw360packager"
  end

  config.vm.provision "shell",
                      inline: <<-SHELL
add-apt-repository ppa:openjdk-r/ppa
apt-get update
apt-get remove -y openjdk-7-jdk
apt-get install -y git wget unzip ruby-dev gcc make maven openjdk-8-jdk rpm
update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
echo "JAVA_HOME=\"/usr/lib/jvm/java-8-openjdk-amd64/jre\"" >> /etc/environment
SHELL

  if ENV['SW360SOURCE'] and File.directory?(File.expand_path(ENV['SW360SOURCE']))
    config.vm.provision "shell",
                        inline: <<-SHELL
wget -q http://dl.bintray.com/apache/thrift/debian/pool/main/t/thrift/thrift-compiler_0.9.3_amd64.deb -O thrift-compiler.deb
dpkg -i thrift-compiler.deb && rm thrift-compiler.deb
ln -s /usr/bin/thrift /usr/local/bin/thrift
SHELL
  end

  config.vm.provision "shell",
                      privileged: "false",
                      inline: <<-SHELL
echo "gem: --no-ri --no-rdoc" > ~/.gemrc
gem install rake fpm
SHELL

  config.vm.synced_folder ".", "/home/vagrant/chore/",
                          type: "rsync",
                          rsync__auto: false,
                          rsync__exclude: [".git/", "_*"]
  config.vm.synced_folder "_cache", "/home/vagrant/chore/_cache"
  config.vm.synced_folder "_output", "/home/vagrant/chore/_output"

  config.vm.provision "shell",
                      privileged: "false",
                      run: "always",
                      inline: <<-SHELL
set -ex

sudo su - vagrant -c "cd /home/vagrant/chore && \
  rake clean package:all"
SHELL

  if ENV['SW360SOURCE'] and File.directory?(File.expand_path(ENV['SW360SOURCE']))
    config.vm.synced_folder File.expand_path(ENV['SW360SOURCE']), "/home/vagrant/sw360portal/",
                            type: "rsync",
                            rsync__auto: false,
                            rsync__exclude: [".git/", "_*", "*.iml", ".idea", "target"]

    config.vm.provision "shell",
                        privileged: "false",
                        run: "always",
                        inline: <<-SHELL
set -ex
mkdir -p /vagrant_shared/output

sudo su - vagrant -c "cd /home/vagrant/sw360portal && \
  DOCKERIZE=false rake clean package:all"
cp /home/vagrant/sw360portal/sw360*.{deb,rpm,gz} /home/vagrant/chore/_output
SHELL
  end
end
